module DEVS
  # This class represents a message that belong to a {Model} through a {Port}.
  # It wraps the payload generated by a model output
  class Message
    attr_reader :payload, :port

    def initialize(payload, port)
       @payload = payload
       @port = port
    end

    def ==(other)
      @port == other.port
    end

    def to_a
      [@payload, @port]
    end

    def to_s
      "message #{@payload}"
    end
  end
end
